language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Codecov
  - sudo pip install codecov
  - ./install_oclint.sh

script: 
  - qmake
  - make
  - ./RibiUnitsTest
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - bash <(curl -s https://codecov.io/bash)

