language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

script: 
  - qmake
  - make
  - ./RibiUnitsTest
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

